export interface AllContractTypes {
  _id: string
  Type: string
  Identity: string
  Name: string
  AdditionalName: string
  Phone: string
  Email: string
  TaxNumber: string
  Mobile: string
  AdditionalPhone: string
  Website: string
  Agent: string
  RepresentationDocument: string
  IdNumber: string
  DocumentNumber: string
  MobileNumber: string
  DocumentDate: string
  ContractNumber: string
  ContractCopy: string
  RelyOn: string
  ContractReleaseDate: string
  ContractEndDate: string
  ContractDate: string
  PaymentWay: string
  TotalPrice: number
  Price: number
  FixedPrice: number
  Times: number
  createdAt: string
  updatedAt: string
  __v: number
  DocumentDateH: string
  ContractReleaseDateH: string
  ContractEndDateH: string
  id: string
  IsRuning: boolean
}
